sudo: required

language: csharp
mono: none
dotnet: 3.1.300
services:
  - docker

install:
  - dotnet restore ./src/Foodopedia.sln

script:
  - dotnet build ./src/Foodopedia.sln -c Release
  - dotnet test ./src/Foodopedia.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_success:
  - docker build -t andrevitorlopes/foodopedia .
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push andrevitorlopes/foodopedia

after_script: 
  # Push codecoverage results to Codecov
  - bash <(curl -s https://codecov.io/bash)